### ISSUE TITLE
character issue when storing or scraping 

### ISSUE THREAD

**Issue by cypriotxx** [SergeiKlimenko/Bible-downloader#2]
14Kɛ́ aa gɛ̃̀ wɛ̃́lɛpiu, ↄ̃ aa kpàaũ ń Samuɛlio gↄ̃̀ↄ, à bↄ̀ lɛ́ gɛ́ gulɛsĩpiu.
15E Saulu àↄ gɛ́ mↄ́i, Dii dↄ̀aa à yã́pi kã̀ Samuɛliɛ a swã́wa à mɛ̀:
16Zia maa'i má Bɛ̃yãmɛɛ bùsu gbɛ̃́ zĩma. Ní nísikawà ǹ aà dilɛ ma gbɛ̃́ Isailiↄ dↄaana ũ, i ma gbɛ̃́piↄ bↄ Filitɛ̃ↄ ↄzĩ. Ma a gbɛ̃́piↄ wii mà, ↄ̃ ma ń wɛgwà.
17Kɛ́ Samuɛli Saulu è, Dii òɛ̀: Gbɛ̃́ pↄ́ ma aà yã'ònɛpin we. Ɔ̃mɛ a kible ma gbɛ̃́ↄwa.
18Ɔ̃ Saulu sↄ̃̀ Samuɛlizi wɛ̃́lɛ bↄlɛu, à aà là à mɛ̀: Gu'ena bɛ ku má ni? Ɔlↄmɛɛ.
19Ɔ̃ Samuɛli wèwà à mɛ̀: Mámɛ má aà ũ. Dↄaa wà gɛ́ gulɛsĩu, ńyↄ̃ pↄblemanↄ gbãɛ. Zia kↄↄ má n nↄ̀sɛ yã'onɛ píi, mí n gbaɛ.
20Ńsu bílikɛ n zàa'ĩna pↄ́ kↄ̀lɛ a gↄↄ àaↄ̃den gbãↄ yã́wao, asa wà ń é. Isaili bùsu pↄmaaↄ píi a gↄ̃ dé pↄ́ ũɛ, mɛ́ i kɛ mpi ń n de bɛdeↄ píi bàasio?
21Ɔ̃ Saulu mɛ̀: Bɛ̃yãmɛɛ buin ma ũo lò? Ma bui mɛ́ fɛ̃́nɛũ dɛ Isaili buiↄla píi, mɛ́ ma daɛↄ mɛ́ kɛ̃́sãańzi Bɛ̃yãmɛɛ buiↄ guu. Bↄ́yãi ńlɛ yã́ bee taa oimɛɛi?
22Ɔ̃ Samuɛli Saulu ń a zĩkɛnao sɛ̀ à gɛ̃̀ńnↄ pↄblekpɛu, à zↄ̃lɛkĩi maa kpàmá gbɛ̃́ pↄ́ wà ń sisiↄ guu. Gbɛ̃́piↄ kà gbɛ̃ↄn baakwi taa.
23Ɔ̃ Samuɛli ò blɛkɛnaɛ: Nↄ̀ↄ pↄ́ má kpàma ma mɛ̀ ǹ a dilɛkĩi kɛpi sɛ mↄò.
24Ɔ̃ blɛkɛnapi mↄ̀ ń nↄ̀ↄ gbadↄmplɛwapio, a dìlɛ Saulu aɛ. Ɔ̃ Samuɛli mɛ̀: Pↄ́ pↄ́ wa dìlɛnɛn kɛ. Só, asa wa dìlɛnɛ ǹ so maa'iɛ ń gbɛ̃́ pↄ́ ma ń sisiↄ. Ɔ̃ Saulu pↄblè ń Samuɛlio zĩbeezĩ.
25Kɛ́ aa pìla gulɛsĩpiwa aa gɛ̃̀ wɛ̃́lɛ ɛu, ↄ̃ Samuɛli gɛ̀ yã'ò ń Sauluo a kpɛ́ musu.
26Ɔ̃ aa ì we. Kɛ́ gu ye dↄi, ↄ̃ Samuɛli lɛzù Sauluzi kpɛ́ musu we à mɛ̀: Fɛlɛ mà gɛ́ zɛinɛ. Kɛ́ Saulu fɛ̀lɛ, aàpi ń Samuɛlio aa bↄ̀ bàasi ḿpla.
27Kɛ́ aa kà wɛ̃́nkpɛ, ↄ̃ Samuɛli ò Sauluɛ: O n zĩkɛnaɛ aàↄ gɛ́, mpi ǹ zɛ gĩa mà yã́ pↄ́ Dii ò onɛ.

**Comment by SergeiKlimenko** [comment]
Which characters do you mean exactly? I've checked this translation (Bibeli Luayãtaalá in Boko). The output file seems to contain precisely the same strings, with the only exception being the character ↄ̃ which looks as if it is represented as two characters, but it's not. Although, I might have missed something else.
